package com.rm.toolkit.mediaStorage.command.security;

public enum AuthorityType {
    AUTHORIZATION,
    CONFIRMED_AVATAR,
    AVATAR_UPLOADED,
    EMPLOYEE_LIST,
    EMPLOYEE_CARD,
    USER_STATUS_SETTINGS,
    USER_CREATED,
    ADD_EMPLOYEE_TO_DEPARTMENT,
    ONE_TO_ONE,
    EDIT_FEEDBACKS,
    ASSESSMENT_GOALS,
    EDIT_COMMENTS,
    VIEW_ONE_TO_ONE,
    VIEW_FEEDBACKS,
    VIEW_ASSESSMENT_GOALS,
    VIEW_COMMENTS,
    VIEW_ROLES,
    VIEW_DEPARTMENTS,
    VIEW_INTERVALS,
    EDIT_DEPARTMENTS,
    EDIT_ROLES,
    EDIT_INTERVALS
}

