UPDATE ROLE
set authorities ='{AUTHORIZATION,VIEW_ROLES,VIEW_DEPARTMENTS,EMPLOYEE_LIST,VIEW_INTERVALS, EDIT_COMMENTS}'
WHERE id = '579fc993-6123-419a-ae3c-96b0b230f834';

UPDATE ROLE
set authorities = '{AUTHORIZATION,VIEW_ROLES,VIEW_DEPARTMENTS,EMPLOYEE_LIST,ONE_TO_ONE, EDIT_FEEDBACKS,
              ASSESSMENT_GOALS,EDIT_COMMENTS,VIEW_INTERVALS}'
WHERE id = '9d859c1c-b5f8-4db6-99cd-2784368d4178';

UPDATE ROLE
set authorities = '{AUTHORIZATION,VIEW_ROLES,VIEW_DEPARTMENTS,EMPLOYEE_LIST,ONE_TO_ONE, EDIT_FEEDBACKS,
              ASSESSMENT_GOALS,EDIT_COMMENTS,EMPLOYEE_CARD,VIEW_INTERVALS}'
WHERE id = '0fea835f-dfbe-400a-bb46-b0a815d2493b';

UPDATE ROLE
set authorities = '{AUTHORIZATION,VIEW_ROLES,VIEW_DEPARTMENTS,EMPLOYEE_LIST,ONE_TO_ONE, EDIT_FEEDBACKS,
                              ASSESSMENT_GOALS,EDIT_COMMENTS,EMPLOYEE_CARD,VIEW_INTERVALS}'
WHERE id = 'a7626246-bc25-4671-9f21-710a1e83f914';

UPDATE ROLE
set authorities = '{AUTHORIZATION,VIEW_ROLES,VIEW_DEPARTMENTS,EMPLOYEE_LIST,ONE_TO_ONE, EDIT_FEEDBACKS,
                              ASSESSMENT_GOALS,EDIT_COMMENTS,EMPLOYEE_CARD,USER_STATUS_SETTINGS,
                              ADD_EMPLOYEE_TO_DEPARTMENT,VIEW_INTERVALS}'
WHERE id = '43b768e7-c117-4da6-9f41-9b6497aa7b31';

UPDATE ROLE
set authorities = '{AUTHORIZATION,EMPLOYEE_LIST,EMPLOYEE_CARD,USER_STATUS_SETTINGS,
                              ADD_EMPLOYEE_TO_DEPARTMENT,VIEW_ONE_TO_ONE,VIEW_FEEDBACKS,VIEW_ASSESSMENT_GOALS,
                              VIEW_COMMENTS,VIEW_ROLES,VIEW_DEPARTMENTS,EDIT_DEPARTMENTS,EDIT_ROLES,EDIT_INTERVALS,
                              EDIT_COMMENTS}'
WHERE id = '96a9b5e3-f523-499f-87ad-ed9f7c17be4a';