server:
  forward-headers-strategy: framework

spring:
  application:
    name: comment-command-service
  datasource:
    driver-Class-Name: org.postgresql.Driver
    hikari:
      leak-detection-threshold: 30000
    username: postgres
    password: admin
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
  kafka:
    consumer:
      group-id: comment-command-service
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  flyway:
    locations:
      - classpath:db/migration
    baseline-on-migrate: true

eureka:
  instance:
    prefer-ip-address: true

management:
  endpoint:
    restart:
      enabled: true
    shutdown:
      enabled: true
    env:
      post:
        enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

authentication:
  token:
    key: ${JWT_KEY}
    issuer: rmt_mobile_auth
    type: Bearer

kafka:
  topic:
    comment: rmt-mobile.comment