spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: andersen.lab.toolkit@gmail.com
    password: test1334
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
